export const TODO_GET_REQUEST = "TODO_GET_REQUEST"
export const TODO_GET_SUCCESS = "TODO_GET_SUCCESS"
export const TODO_GET_ERROR = "TODO_GET_ERROR"

export const TODO_ADD_REQUEST = "TODO_ADD_REQUEST"
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS"
export const TODO_ADD_ERROR = "TODO_ADD_ERROR"

export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST"
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS"
export const TODO_DELETE_ERROR = "TODO_DELETE_ERROR"

export const TODO_UPDATE_REQUEST = "TODO_UPDATE_REQUEST"
export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS"
export const TODO_UPDATE_ERROR = "TODO_UPDATE_ERROR"

export const TODO_TOGGLE_COMPLETION_REQUEST = "TODO_TOGGLE_COMPLETION_REQUEST";
export const TODO_TOGGLE_COMPLETION_SUCCESS = "TODO_TOGGLE_COMPLETION_SUCCESS";
export const TODO_TOGGLE_COMPLETION_ERROR = "TODO_TOGGLE_COMPLETION_ERROR";
